/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forca;
import java.util.Random;
/**
 *
 * @author Fernanda
 */
public class Forca extends javax.swing.JFrame {
    
    String letra = "", palavraIn = "";
    int tentativas = 0, sorteioT = 0, erros=0;
        
    Random tema = new Random();
        
    // Criação de vetores para os temas
    String animal[] = {"gaivota", "tartaruga", "cachorro", "girafa", "elefante"};
    String cor[] = {"rosa", "preto", "azul", "amarelo", "vermelho"};
    String alimento[] = {"arroz", "feijao", "pao", "carne", "frango"};
    /**
     * Creates new form Forca
     */
    public Forca() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNovoJ = new javax.swing.JButton();
        lbTema = new javax.swing.JLabel();
        lbEspace1 = new javax.swing.JLabel();
        lbEspace2 = new javax.swing.JLabel();
        lbEspace3 = new javax.swing.JLabel();
        lbEspace4 = new javax.swing.JLabel();
        lbEspace5 = new javax.swing.JLabel();
        lbEspace6 = new javax.swing.JLabel();
        lbEspace7 = new javax.swing.JLabel();
        lbEspace8 = new javax.swing.JLabel();
        lbEspace9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfLetra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbLetrasDigitadas = new javax.swing.JLabel();
        lbMensagens = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btNovoJ.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btNovoJ.setText("Novo Jogo");
        btNovoJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoJActionPerformed(evt);
            }
        });

        lbTema.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTema.setText("-Tema-");

        lbEspace1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace1.setText("_");

        lbEspace2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace2.setText("_");

        lbEspace3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace3.setText("_");

        lbEspace4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace4.setText("_");

        lbEspace5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace5.setText("_");

        lbEspace6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace6.setText("_");

        lbEspace7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace7.setText("_");

        lbEspace8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace8.setText("_");

        lbEspace9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbEspace9.setText("_");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Digite uma letra: ");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Tentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbLetrasDigitadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLetrasDigitadas.setText("-Letras digitadas-");

        lbMensagens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMensagens.setText("-mensagens-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLetrasDigitadas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btNovoJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMensagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(lbEspace1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace2)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace3)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace4)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace5)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace6)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace7)
                                .addGap(18, 18, 18)
                                .addComponent(lbEspace8)))
                        .addGap(18, 18, 18)
                        .addComponent(lbEspace9)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEspace2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEspace1))
                    .addComponent(lbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(lbMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbLetrasDigitadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovoJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //void criado para o sorteio do tema
    public void sorteio(String tema){
        lbTema.setText(tema);
        Random palavra=new Random();
        int sorteioP=palavra.nextInt(5);
        
    if (sorteioT==0){
        palavraIn=animal[sorteioP];
    }if (sorteioT==1){
        palavraIn=cor[sorteioP];
    }if (sorteioT==2){
        palavraIn=alimento[sorteioP];
    }
    }
            
    private void btNovoJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoJActionPerformed
    
    sorteioT=tema.nextInt(3);
    lbLetrasDigitadas.setText("");
    lbMensagens.setText("");
    tfLetra.requestFocus();
    erros=0;
 
    if (sorteioT==0){
        sorteio("Animal");
    }if (sorteioT==1){
        sorteio("Cor");
    }if (sorteioT==2){
        sorteio("Alimento");
    }
    //System.out.println(palavraIn);
    
    int tamanho = palavraIn.length();
    if(tamanho==3){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("");
        lbEspace5.setText("");
        lbEspace6.setText("");
        lbEspace7.setText("");
        lbEspace8.setText("");
        lbEspace9.setText("");
    } if(tamanho==4){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("_");
        lbEspace5.setText("");
        lbEspace6.setText("");
        lbEspace7.setText("");
        lbEspace8.setText("");
        lbEspace9.setText("");
    } if(tamanho==5){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("_");
        lbEspace5.setText("_");
        lbEspace6.setText("");
        lbEspace7.setText("");
        lbEspace8.setText("");
        lbEspace9.setText("");
    } if(tamanho==6){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("_");
        lbEspace5.setText("_");
        lbEspace6.setText("_");
        lbEspace7.setText("");
        lbEspace8.setText("");
        lbEspace9.setText("");
    } if(tamanho==7){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("_");
        lbEspace5.setText("_");
        lbEspace6.setText("_");
        lbEspace7.setText("_");
        lbEspace8.setText("");
        lbEspace9.setText("");
    } if(tamanho==8){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("_");
        lbEspace5.setText("_");
        lbEspace6.setText("_");
        lbEspace7.setText("_");
        lbEspace8.setText("_");
        lbEspace9.setText("");
    } if(tamanho==9){
        lbEspace1.setText("_");
        lbEspace2.setText("_");
        lbEspace3.setText("_");
        lbEspace4.setText("_");
        lbEspace5.setText("_");
        lbEspace6.setText("_");
        lbEspace7.setText("_");
        lbEspace8.setText("_");
        lbEspace9.setText("_");
    }
    }//GEN-LAST:event_btNovoJActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String letrasDigitadas = "";
        int posL = 0, pos=0, i=0, posicao=0, seq=0;
        
        if(erros >= 7){
            lbMensagens.setText("Você perdeu! Mais inteligência na próxima. A palavra era: "+ palavraIn);
        } else {
        lbMensagens.setText("");
        letra = tfLetra.getText().toLowerCase();
        
    letrasDigitadas = lbLetrasDigitadas.getText();    
    posL = letrasDigitadas.indexOf(letra,posL);
    
    
    if(posL!=-1){
        lbMensagens.setText("Essa letra ja foi digitada!");
        tfLetra.setText("");
        tfLetra.requestFocus();
    } 
            else{
        lbLetrasDigitadas.setText(lbLetrasDigitadas.getText()+letra+" - ");
        pos = palavraIn.indexOf(letra,pos);
        tfLetra.setText("");
        tfLetra.requestFocus();
        //contagem de erro(arrumar)
        if(pos==-1){
            lbMensagens.setText("Letra não encontrada!");
            erros++;
            System.out.println(erros);
        }else{
            for(pos=0;pos < palavraIn.length();pos++){
                if(palavraIn.substring(pos, pos++).equals(letra)){
                    System.out.println(palavraIn.substring(pos,pos + 1));
                }
            }
        while(i <palavraIn.length()){
            i++;
            posicao = palavraIn.indexOf(letra,posicao);
            
            switch(posicao){
            case 0:
                lbEspace1.setText(letra);
                posicao++;
                seq++;
                continue;
            
            case 1:
                lbEspace2.setText(letra);
                posicao++;
                seq++;
                continue;
                
            case 2:
                lbEspace3.setText(letra);
                posicao++;
                seq++;
                continue;
            
            case 3:
                lbEspace4.setText(letra);
                posicao++;
                seq++;
                continue;
                
            case 4:
                lbEspace5.setText(letra);
                posicao++;
                seq++;
                continue;
                
            case 5:
                lbEspace6.setText(letra);
                posicao++;
                seq++;
                continue;
                
            case 6:
                lbEspace7.setText(letra);
                posicao++;
                seq++;
                continue;
                
            case 7:
                lbEspace8.setText(letra);
                posicao++;
                seq++;
                continue;
                
            case 8:
                lbEspace9.setText(letra);
                posicao++;
                seq++;
                        }
                    }
                }
        if ((!lbEspace1.getText().equals("_"))&& (!lbEspace1.getText().equals("_"))&& (!lbEspace2.getText().equals("_"))&& (!lbEspace3.getText().equals("_"))&& (!lbEspace4.getText().equals("_"))&& (!lbEspace5.getText().equals("_"))&& (!lbEspace6.getText().equals("_"))&& (!lbEspace7.getText().equals("_"))&& (!lbEspace8.getText().equals("_"))&& (!lbEspace9.getText().equals("_"))){
                lbMensagens.setText("PARABÉNS VOCÊ VENCEU!!!!!!!!!!!!!!!!!!");
            }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovoJ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEspace1;
    private javax.swing.JLabel lbEspace2;
    private javax.swing.JLabel lbEspace3;
    private javax.swing.JLabel lbEspace4;
    private javax.swing.JLabel lbEspace5;
    private javax.swing.JLabel lbEspace6;
    private javax.swing.JLabel lbEspace7;
    private javax.swing.JLabel lbEspace8;
    private javax.swing.JLabel lbEspace9;
    private javax.swing.JLabel lbLetrasDigitadas;
    private javax.swing.JLabel lbMensagens;
    private javax.swing.JLabel lbTema;
    private javax.swing.JTextField tfLetra;
    // End of variables declaration//GEN-END:variables
}
