/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author Anchieta
 */
public class tela extends javax.swing.JFrame {
    String jogador = "O";
    int pontoX = 0, pontoO = 0;
    
    String espaco01 = "-", espaco02 = "-", espaco03 = "-", espaco04 = "-", espaco05 = "-", espaco06 = "-", espaco07 = "-", espaco08 = "-", espaco09 = "-";
    
    
    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        espaco1 = new javax.swing.JButton();
        espaco2 = new javax.swing.JButton();
        espaco4 = new javax.swing.JButton();
        espaco5 = new javax.swing.JButton();
        espaco6 = new javax.swing.JButton();
        espaco3 = new javax.swing.JButton();
        espaco8 = new javax.swing.JButton();
        espaco9 = new javax.swing.JButton();
        espaco7 = new javax.swing.JButton();
        btNovoJogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPontoX = new javax.swing.JLabel();
        lbPontoO = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("O");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        espaco1.setText("-");
        espaco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco1ActionPerformed(evt);
            }
        });

        espaco2.setText("-");
        espaco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco2ActionPerformed(evt);
            }
        });

        espaco4.setText("-");
        espaco4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco4ActionPerformed(evt);
            }
        });

        espaco5.setText("-");
        espaco5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco5ActionPerformed(evt);
            }
        });

        espaco6.setText("-");
        espaco6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco6ActionPerformed(evt);
            }
        });

        espaco3.setText("-");
        espaco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco3ActionPerformed(evt);
            }
        });

        espaco8.setText("-");
        espaco8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco8ActionPerformed(evt);
            }
        });

        espaco9.setText("-");
        espaco9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco9ActionPerformed(evt);
            }
        });

        espaco7.setText("-");
        espaco7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco7ActionPerformed(evt);
            }
        });

        btNovoJogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btNovoJogo.setText("Novo jogo");
        btNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoJogoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vitórias");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("X -");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("O -");

        lbPontoX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPontoX.setText("0");

        lbPontoO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPontoO.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(espaco1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(espaco2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(espaco3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espaco4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(espaco8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(espaco9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(espaco5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(espaco6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(lbPontoO))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPontoX)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNovoJogo)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espaco1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espaco5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espaco8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPontoX, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPontoO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btNovoJogo)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoJogoActionPerformed
        // TODO add your handling code here:
        espaco1.setText("-");
        espaco2.setText("-");
        espaco3.setText("-");
        espaco4.setText("-");
        espaco5.setText("-");
        espaco6.setText("-");
        espaco7.setText("-");
        espaco8.setText("-");
        espaco9.setText("-");
      
    //PONTO PARA O X   
    if(espaco01.equals("X") && espaco02.equals("X") && espaco03.equals("X")){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco04.equals("X")) && (espaco05.equals("X")) && (espaco06.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco07.equals("X")) && (espaco08.equals("X")) && (espaco09.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco01.equals("X")) && (espaco04.equals("X")) && (espaco07.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco02.equals("X")) && (espaco05.equals("X")) && (espaco08.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco03.equals("X")) && (espaco06.equals("X")) && (espaco09.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco01.equals("X")) && (espaco05.equals("X")) && (espaco09.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    } if((espaco03.equals("X")) && (espaco05.equals("X")) && (espaco07.equals("X"))){
        pontoX++;
        lbPontoX.setText("" + pontoX);
    }
    
    
    //PONTO PARA O O
    if((espaco01.equals("O")) && (espaco02.equals("O")) && (espaco03.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco04.equals("O")) && (espaco05.equals("O")) && (espaco06.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco07.equals("O")) && (espaco08.equals("O")) && (espaco09.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco01.equals("O")) && (espaco04.equals("O")) && (espaco07.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco02.equals("O")) && (espaco05.equals("X")) && (espaco08.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco03.equals("O")) && (espaco06.equals("O")) && (espaco09.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco01.equals("O")) && (espaco05.equals("O")) && (espaco09.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    } if((espaco03.equals("O")) && (espaco05.equals("O")) && (espaco07.equals("O"))){
        pontoO++;
        lbPontoO.setText("" + pontoO);
    }
    }//GEN-LAST:event_btNovoJogoActionPerformed

    private void espaco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco1ActionPerformed
        // TODO add your handling code here:
         if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
         
         if (jogador.equals("X")){
             espaco1.setText("X");
         } else {
             espaco1.setText("O");
         }
             espaco01 = espaco1.getText();
    }//GEN-LAST:event_espaco1ActionPerformed
  
    private void espaco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco2ActionPerformed
        // TODO add your handling code here:
         if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
         
         if (jogador.equals("X")){
             espaco2.setText("X");
         } else {
             espaco2.setText("O");
         }
         espaco02 = espaco2.getText();
    }//GEN-LAST:event_espaco2ActionPerformed

    private void espaco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco3ActionPerformed
        // TODO add your handling code here:
         if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
         
         if (jogador.equals("X")){
             espaco3.setText("X");
         } else {
             espaco3.setText("O");
         }
         
         espaco03 = espaco3.getText();
    }//GEN-LAST:event_espaco3ActionPerformed

    private void espaco4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco4ActionPerformed
        // TODO add your handling code here:
         if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
         
         if (jogador.equals("X")){
             espaco4.setText("X");
         } else {
             espaco4.setText("O");
         }
         espaco04 = espaco4.getText();
         
    }//GEN-LAST:event_espaco4ActionPerformed

    private void espaco5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco5ActionPerformed
        // TODO add your handling code here:
        if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
        
        if (jogador.equals("X")){
             espaco5.setText("X");
         } else {
             espaco5.setText("O");
         }
        espaco05 = espaco5.getText();
    }//GEN-LAST:event_espaco5ActionPerformed

    private void espaco6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco6ActionPerformed
        // TODO add your handling code here:
        if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
        
        if (jogador.equals("X")){
             espaco6.setText("X");
         } else {
             espaco6.setText("O");
         }
        espaco06 = espaco6.getText();
    }//GEN-LAST:event_espaco6ActionPerformed

    private void espaco7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco7ActionPerformed
        // TODO add your handling code here:
        if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
        
        if (jogador.equals("X")){
             espaco7.setText("X");
         } else {
             espaco7.setText("O");
         }
        
        espaco07 = espaco7.getText();
    }//GEN-LAST:event_espaco7ActionPerformed

    private void espaco8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco8ActionPerformed
        // TODO add your handling code here:
        if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
        
        if (jogador.equals("X")){
             espaco8.setText("X");
         } else {
             espaco8.setText("O");
         }
        espaco08 = espaco8.getText();
    }//GEN-LAST:event_espaco8ActionPerformed

    private void espaco9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco9ActionPerformed
        // TODO add your handling code here:
        if(jogador.equals("X")){
            jogador = "O";
        } else {
            jogador = "X";
        }
        
        if (jogador.equals("X")){
             espaco9.setText("X");
         } else {
             espaco9.setText("O");
         }
        
        espaco09 = espaco9.getText();
    }//GEN-LAST:event_espaco9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovoJogo;
    private javax.swing.JButton espaco1;
    private javax.swing.JButton espaco2;
    private javax.swing.JButton espaco3;
    private javax.swing.JButton espaco4;
    private javax.swing.JButton espaco5;
    private javax.swing.JButton espaco6;
    private javax.swing.JButton espaco7;
    private javax.swing.JButton espaco8;
    private javax.swing.JButton espaco9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbPontoO;
    private javax.swing.JLabel lbPontoX;
    // End of variables declaration//GEN-END:variables
}
